config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root to: 'main#dashboard'

  devise_for :users

  resources :users, only: :index
  resources :foods
  resources :orders

  namespace :api do
    namespace :v1 do
      resources :orders, only: %i[index show]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user
    return guest_abilities unless user
    return admin_abilities if user.admin?

    user_abilities
  end

  def guest_abilities
    can :read, Food
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities

    can :read, Food

    can :create, Order
    can %i[read update], Order, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  CATEGORIES = [1, 2, 3].freeze

  has_many :food_orders
  has_many :orders, through: :food_orders

  has_one_attached :image

  validates :title, :category, :price, presence: true

  scope :on_date, ->(date) { where('date = ?', date) }

  def self.weak_days
    %w[Monday Tuesday Wednesday	Thursday Friday Saturday Sunday]
  end

  def self.weak_dates(date = Time.current.to_date)
    (date.beginning_of_week..date.end_of_week).to_a
  end
end

app/models/food_order.rb
class FoodOrder < ApplicationRecord
  belongs_to :food
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  STATUSES = %w[forming processing performed].freeze

  belongs_to :user
  has_many :food_orders
  has_many :foods, through: :food_orders

  attribute :date, :date, default: Time.current.to_date
  attribute :status, :string, default: STATUSES.first
  validates :status, presence: true, inclusion: { in: STATUSES }

  before_create :destroy_old_forming_orders

  scope :on_date, ->(date) { where(date: date).where.not(status: STATUSES.first) }

  def self.find_forming_or_create
    find_or_create_by(status: STATUSES.first)
  end

  def self.total_cost(date: Time.current.to_date)
    on_date(date).sum(&:total_price)
  end

  def destroy_old_forming_orders
    Order.where(status: STATUSES.first).destroy_all
  end

  def calculate_total_price
    update_attribute :total_price, foods.sum(:price)
  end

  def can_add?(food)
    return false if food.date != Time.current.to_date
    return false if foods.include? food
    return false if foods.map(&:category).include? food.category

    true
  end

  def add_food(food)
    return unless food
    return unless can_add?(food)

    foods.push food
    calculate_total_price
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :orders

  validates :email, presence: true

  before_create :set_admin, unless: -> { User.exists? }

  private

  def set_admin
    self.admin = true
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  # skip_authorization_check

  before_action :doorkeeper_authorize!

  private

  def current_resource_owner
    @current_resource_owner ||= User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end

  alias current_user current_resource_owner
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::BaseController
  before_action :set_order, only: :show

  authorize_resource

  def index
    @orders = Order.on_date(Time.current.to_date)
    render json: @orders
  end

  def show
    render json: @order
  end

  private

  def set_order
    @order = Order.find(params['id'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    if current_user
      respond_to do |format|
        format.html { redirect_to root_url, alert: exception.message }
        format.js { render params[:action], status: :unauthorized }
        format.json { render json: {}, status: :unauthorized }
      end
    else
      session[:next] = request.fullpath
      redirect_to new_user_session_path, alert: 'You have to log in to continue.'
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show edit update destroy]

  authorize_resource

  def index
    @date = params[:date] || Time.current.to_date
    @foods = Food.on_date(@date)
  end

  def new
    @food = Food.new(date: Time.current.to_date)
  end

  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to root_path, notice: 'Food was successfuly created.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @food.update(food_params)
      redirect_to root_path, notice: 'Food was successfuly updated.'
    else
      render :edit
    end
  end

  def destroy
    @food.destroy

    redirect_to foods_path, notice: 'Food was successfuly deleted.'
  end

  private

  def set_food
    @food = Food.with_attached_image.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:title, :date, :price, :category, :image)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @weak_days = Food.weak_days
    @weak_dates = Food.weak_dates
    @order = current_user.orders.find_forming_or_create
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dates, only: :index
  before_action :set_order, only: %i[show edit update destroy]

  authorize_resource

  def index
    @orders = Order.on_date(@date)
    @orders = @orders.where(user_id: current_user.id) unless current_user.admin?
  end

  def new
    @order = current_user.orders.new
  end

  def create
    @order = current_user.orders.new(order_params)

    if @order.save
      redirect_to orders_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if params[:food_id]
      food = Food.find(params[:food_id])
      @order.add_food(food)
      redirect_to root_path
    elsif @order.update(order_params)
      redirect_to orders_path
    else
      render :edit
    end
  end

  def destroy
    @order.destroy

    redirect_to orders_path, notice: 'Order was successfuly deleted'
  end

  private

  def set_dates
    @date = (params[:date] || Time.current).to_date
    @prev_date = @date - 1.day
    @next_date = @date + 1.day
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:total_price, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    "Current year: #{Time.current.year}"
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end

  def flash_class(type)
    {
      notice: 'alert-info',
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning'
    }[type.to_sym]
  end

  def auto_format_text(text)
    text ||= simple_format(text)
    text.gsub(URI::DEFAULT_PARSER.make_regexp, '<a href="\0" target= "_blank">\0</a>')
  end

  def icon_button(type = 'close', icon = '&times')
    button_tag(type: 'button', class: type, 'data-dismiss': 'alert', 'aria-label': type) do
      content_tag(:span, icon.try(:html_safe), 'aria-hidden': 'true')
    end
  end

  def text_with_button(text, type = 'close', icon = '&times')
    (
      auto_format_text(text) +
      icon_button(type, icon)
    ).try(:html_safe)
  end

  def show_flash(flash)
    content_tag :p do
      flash.each do |type, message|
        concat(
          content_tag(
            :div, text_with_button(message),
            class: "alert #{flash_class(type)} alert-dismissible fade show", role: 'alert'
          )
        )
      end
    end
  end

  def food_link(food)
    "#{food.title} - #{food.price}$"
  end
end

app/views/foods/_food.html.slim
tr
  th scope='row' class='align-middle'= food.title
  td= link_to image_tag(food.image.variant(resize_to_limit: [100, 100])), url_for(food.image), target: '_blank', title: 'Preview' if food.image.attached?
  td= food.price
  td= food.category
  td= link_to 'Edit', edit_food_path(food),
              class: 'btn btn-outline-primary btn-sm'
  td= link_to 'Delete', food_path(food), method: :delete,
              data: { confirm: 'Are you sure?'}, class: 'btn btn-outline-danger btn-sm'

app/views/foods/_form.html.slim
= form_with model: @food, local: true do |f|
  .food-errors= render 'shared/errors', resource: @food
  .card.border-primary
    .card-body
      .form-group
        .input-group.mb-2
          .input-group-prepend
            span.input-group-text.form-control= f.label :date
          .form-control= @food.date
          = f.hidden_field :date, class: 'form-control'
        .input-group.mb-2
          .input-group-prepend
            span.input-group-text.form-control= f.label :title
          = f.text_field :title, autofocus: true, autocomplete: 'title', class: 'form-control'
        .input-group.mb-2
          .input-group-prepend
            span.input-group-text.form-control= f.label :price
          = f.number_field :price, autofocus: true, autocomplete: 'price', class: 'form-control'
          .input-group-append
            span.input-group-text.form-control $
        .input-group.mb-2
          .input-group-prepend
            span.input-group-text.form-control= f.label :category
          - Food::CATEGORIES.each do |category|
            .input-group-prepend
              span.input-group-text= f.radio_button :category, category
            .form-control= f.label category
        .input-group.mb-2
          .input-group-prepend
            span.input-group-text.form-control= f.label :image
          - if @food.image.attached?
            .form_inline
              = link_to image_tag(@food.image.variant(resize_to_limit: [100, 100])), rails_blob_path(@food.image, disposition: 'attachment'), class: 'form-control'
          = f.file_field :image, multiple: false, direct_upload: true, class: 'form-control'
        .mt-3= f.submit 'Save', class: 'btn btn-primary save-button-link'

app/views/foods/edit.html.slim
.row.justify-content-center
  .col.col-md-7
    h3 Edit Food
    = render 'form'

app/views/foods/index.html.slim
.row.mt-2
  .col-2.h4 Foods
  .col= "on date: #{@date}"

table.table.table-striped.table-bordered
  thead
    tr.table-info
      th scope='col'= Food.human_attribute_name(:title)
      th scope='col'= Food.human_attribute_name(:image)
      th scope='col'= Food.human_attribute_name(:price)
      th scope='col'= Food.human_attribute_name(:category)
      th scope='col' colspan='2' Actions
  tbody
    = render @foods

app/views/foods/new.html.slim
.row.justify-content-center
  .col.col-md-7
    h3 Create Food
    = render 'form'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Lunch Ordering
    meta charset='utf-8'
    meta content='width=device-width, initial-scale=1, shrink-to-fit=no' name='viewport'
    = action_cable_meta_tag
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = render 'shared/nav'
      = show_flash(flash)
      = yield
      = render 'shared/footer'

app/views/main/_admin.html.slim
.mt-3= link_to 'Add Food', new_food_path, title: 'Add food for today', class: 'btn btn-primary new-food-link'

app/views/main/_user.html.slim
.order= render 'orders/order', order: @order
= link_to 'Process order', order_path(@order, 'order[status]' => Order::STATUSES[1]), method: :put, class: 'btn btn-primary'

app/views/main/_weak_days.html.slim
h3.text-center= t(Food.model_name.human)
nav.navbar.navbar-expand-lg.navbar-light.bg-light.p-0.m-0
  button.navbar-toggler aria-controls='navbarFood' aria-expanded='false' aria-label=('Toggle navigation') data-target='#navbarFood' data-toggle='collapse' type='button'
    span.navbar-toggler-icon
  #navbarFood.collapse.navbar-collapse
    ul.navbar-nav.mr-auto.m-2.mt-lg-0
      - @weak_days.each_with_index do |day, i|
        li class="nav-item dropdown #{day}"
          = link_to day, '#', remote: true, id: 'navbarDropdown', class: 'nav-link dropdown-toggle', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', 'role' => 'button'
          .dropdown-menu aria-labelledby='navbarDropdown'
            - Food.on_date(@weak_dates[i]).each do |food|
              - if !current_user.admin? && @order.can_add?(food)
                = link_to order_path(@order, food_id: food.id), method: :put, class: 'dropdown-item', title: 'Add to Order' do
                  span.mr-2= food_link(food)
                  = image_tag(food.image.variant(resize_to_limit: [100, 100])) if food.image.attached?
              - else
                a.dropdown-item.disabled
                  span.mr-2= food_link(food)
                  = image_tag(food.image.variant(resize_to_limit: [100, 100])) if food.image.attached?

app/views/main/dashboard.html.slim
= render 'main/weak_days'
- if current_user.admin?
  .admin_dashboard= render 'main/admin'
- else
  .user_dashboard= render 'main/user'

app/views/orders/_order.html.slim
.row.mt-2 class="order-#{order.id}"
  .col.h4 Order
  .col class="order-total-price-#{order.id}"= "total price: #{order.total_price}"
  .col.small= "on date: #{order.date}"
  .col-3.small= "user: #{order.user.email}"
  .col.small= "status: #{order.status}"

table.table.table-striped.table-bordered
  thead
    tr.table-info
      th scope='col' Food
      th scope='col' Price
  tbody
    - order.foods.each do |food|
      tr
        td= food.title
        td= food.price

app/views/orders/index.html.slim
.row.mt-2
  .col.h4 Orders
  .col class='orders-total-cost'
    b Total cost:
    span.ml-2= @orders.total_cost
  .col= link_to '← prev date', orders_path(date: @prev_date), class: 'prev-orders-link'
  .col= "on date: #{@date}"
  .col= link_to 'next day →', orders_path(date: @next_date), class: 'next-orders-link'
= render @orders

app/views/shared/_errors.html.slim
- if resource.present? && resource.errors.any?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource.try(:id) }
    h4= t('.header', count: resource.errors.count) + ':'
    ul
      - resource.errors.full_messages.each do |message|
        li= message

app/views/shared/_footer.html.slim
footer.bg-light.mt-4
  .row.text-center
    .col.mb-3.mt-3
      h6
        | Project:
        b.ml-2= link_to 'Lunch Ordering', github_url('shilovk', 'lo')
    .w-100
    .col= current_year
    .col
      | Author:
      .ml-2= link_to 'Konstantin Shilov', github_url('shilovk', '')
    .w-100
    small.col.mt-3 About project: Lunch ordering using food orders

app/views/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .navbar-brand= link_to_unless current_page?(root_url), 'Lunch Ordering', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls='navbarMenu' aria-expanded='false' aria-label=('Menu navigation') data-target='#navbarMenu' data-toggle='collapse' type='button'
    span.navbar-toggler-icon
  #navbarMenu.collapse.navbar-collapse
    ul.navbar-nav.mr-auto.mt-2.mt-lg-0
      - if user_signed_in?
        li= link_to 'Orders', orders_path, class: 'nav-item nav-link d-inline list-orders-link'
        - if current_user.admin?
          li= link_to 'Users', users_path, class: 'nav-item nav-link d-inline list-users-link'
          li= link_to 'Foods', foods_path, class: 'nav-item nav-link d-inline'
        li.nav-item.d-inline
          = "<b>#{current_user.email}</b>".html_safe
          span.badge.badge-primary.ml-2= t('.admin') if current_user.admin?
          li= link_to t('.edit'), edit_user_registration_path, class: 'nav-item nav-link d-inline'
        li= link_to t(".sign_out"), destroy_user_session_path, method: :delete, class: 'nav-item nav-link d-inline'
      - else
        - if controller_name != 'registrations'
          li= link_to t('.sign_up'), new_user_registration_path, class: 'nav-item nav-link d-inline'
        - if controller_name != 'sessions'
          li= link_to t('.sign_in'), new_user_session_path, class: 'nav-item nav-link d-inline'

app/views/users/_user.html.slim
tr
  td= user.email
  td= user.name

app/views/users/index.html.slim
.row.mt-2
  .col.h4 Users

table.table.table-striped.table-bordered
  thead
    tr.table-info
      th scope='col' Email
      th scope='col' Name
  tbody
    = render @users